version: '3.4'
services:
    postgres:
        container_name: 'memotopia-api-db'
        image: postgres
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    # nodeapp:
    #   container_name: 'node-app'
    #   build: ./
    #   links:
    #     - 'postgres'
    #   depends_on:
    #     - 'postgres'
    #   ports:
    #     - '80:3001'

volumes:
    dbdata:
        name: memotopia-api-db-volume
